#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ixpdimm_sw
Version  : 01.00.00.2435
Release  : 1
URL      : https://github.com/intel/ixpdimm_sw/releases/download/v01.00.00.2435/ixpdimm_sw-01.00.00.2435.tar.gz
Source0  : https://github.com/intel/ixpdimm_sw/releases/download/v01.00.00.2435/ixpdimm_sw-01.00.00.2435.tar.gz
Source1  : https://github.com/intel/invm-frameworks/archive/4866765923823d140d0df876ecfe1910bf31252d.tar.gz
Source2  : ixpdimm-monitor.service
Summary  : Framework for Storage I18N, CLI and CIM applications
Group    : Development/Tools
License  : BSD-3-Clause BSD-3-Clause-Clear BSL-1.0
Requires: ixpdimm_sw-bin
Requires: ixpdimm_sw-config
Requires: ixpdimm_sw-lib
Requires: ixpdimm_sw-data
Requires: ixpdimm_sw-doc
BuildRequires : cmake
BuildRequires : groff
BuildRequires : ndctl-dev
BuildRequires : numactl-dev
BuildRequires : openssl-dev
BuildRequires : pkgconfig(sqlite3)
BuildRequires : pkgconfig(systemd)
BuildRequires : pkgconfig(zlib)
BuildRequires : python

%description
Framework library supporting a subset of Internationalization (I18N)
functionality, storage command line interface (CLI) applications, storage
common information model (CIM) providers.

%package bin
Summary: bin components for the ixpdimm_sw package.
Group: Binaries
Requires: ixpdimm_sw-data
Requires: ixpdimm_sw-config

%description bin
bin components for the ixpdimm_sw package.


%package config
Summary: config components for the ixpdimm_sw package.
Group: Default

%description config
config components for the ixpdimm_sw package.


%package data
Summary: data components for the ixpdimm_sw package.
Group: Data

%description data
data components for the ixpdimm_sw package.


%package dev
Summary: dev components for the ixpdimm_sw package.
Group: Development
Requires: ixpdimm_sw-lib
Requires: ixpdimm_sw-bin
Requires: ixpdimm_sw-data
Provides: ixpdimm_sw-devel

%description dev
dev components for the ixpdimm_sw package.


%package doc
Summary: doc components for the ixpdimm_sw package.
Group: Documentation

%description doc
doc components for the ixpdimm_sw package.


%package lib
Summary: lib components for the ixpdimm_sw package.
Group: Libraries
Requires: ixpdimm_sw-data

%description lib
lib components for the ixpdimm_sw package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n ixpdimm_sw-01.00.00.2435
mkdir -p %{_topdir}/BUILD/ixpdimm_sw-01.00.00.2435/ZzZz
mv %{_topdir}/BUILD/invm-frameworks-4866765923823d140d0df876ecfe1910bf31252d/* %{_topdir}/BUILD/ixpdimm_sw-01.00.00.2435/ZzZz

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518738262
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1518738262
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/ixpdimm-monitor.service
## make_install_append content
mv %{buildroot}/var/lib/ixpdimm_sw/* %{buildroot}/usr/share/ixpdimm_sw/
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ixpdimm-cli
/usr/bin/ixpdimm-monitor

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/ixpdimm-monitor.service

%files data
%defattr(-,root,root,-)
/usr/share/ixpdimm_sw/Pegasus/mof/intelwbem.mof
/usr/share/ixpdimm_sw/Pegasus/mof/pegasus_register.mof
/usr/share/ixpdimm_sw/Pegasus/mof/profile_registration.mof
/usr/share/ixpdimm_sw/apss.dat
/usr/share/ixpdimm_sw/public.rev0.pem
/usr/share/ixpdimm_sw/sfcb/INTEL_NVDIMM.reg
/usr/share/ixpdimm_sw/sfcb/sfcb_intelwbem.mof

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/libinvm-cim/AssociationFactory.h
/usr/include/libinvm-cim/AssociationMapper.h
/usr/include/libinvm-cim/Attribute.h
/usr/include/libinvm-cim/CimXml.h
/usr/include/libinvm-cim/CimomAdapter.h
/usr/include/libinvm-cim/CmpiAdapter.h
/usr/include/libinvm-cim/Exception.h
/usr/include/libinvm-cim/ExceptionBadAttribute.h
/usr/include/libinvm-cim/ExceptionBadParameter.h
/usr/include/libinvm-cim/ExceptionInvalidWqlQuery.h
/usr/include/libinvm-cim/ExceptionNoMemory.h
/usr/include/libinvm-cim/ExceptionNotSupported.h
/usr/include/libinvm-cim/ExceptionSystemError.h
/usr/include/libinvm-cim/Export.h
/usr/include/libinvm-cim/IndicationService.h
/usr/include/libinvm-cim/Instance.h
/usr/include/libinvm-cim/InstanceFactory.h
/usr/include/libinvm-cim/InstanceFactoryCreator.h
/usr/include/libinvm-cim/IntelCmpiProvider.h
/usr/include/libinvm-cim/IntelToCmpi.h
/usr/include/libinvm-cim/Logger.h
/usr/include/libinvm-cim/NullInstanceFactory.h
/usr/include/libinvm-cim/ObjectPath.h
/usr/include/libinvm-cim/ObjectPathBuilder.h
/usr/include/libinvm-cim/ProviderFactory.h
/usr/include/libinvm-cim/StringUtil.h
/usr/include/libinvm-cim/Strings.h
/usr/include/libinvm-cim/Trace.h
/usr/include/libinvm-cim/Types.h
/usr/include/libinvm-cim/WqlConditional.h
/usr/include/libinvm-cim/WqlQuery.h
/usr/include/libinvm-cim/common_types.h
/usr/include/libinvm-cim/logging.h
/usr/include/libinvm-cim/revision.h
/usr/include/libinvm-cim/s_str.h
/usr/include/libinvm-cim/time_utilities.h
/usr/include/libinvm-cim/unicode_utilities.h
/usr/include/libinvm-cim/x_str.h
/usr/include/libinvm-cli/CliFrameworkTypes.h
/usr/include/libinvm-cli/CommandFilter.h
/usr/include/libinvm-cli/CommandSpec.h
/usr/include/libinvm-cli/CommandVerify.h
/usr/include/libinvm-cli/DuplicateTokenErrorResult.h
/usr/include/libinvm-cli/ErrorResult.h
/usr/include/libinvm-cli/Export.h
/usr/include/libinvm-cli/FeatureBase.h
/usr/include/libinvm-cli/FeatureRef.h
/usr/include/libinvm-cli/Framework.h
/usr/include/libinvm-cli/HelpFeature.h
/usr/include/libinvm-cli/HelpResult.h
/usr/include/libinvm-cli/Lexer.h
/usr/include/libinvm-cli/Logger.h
/usr/include/libinvm-cli/NoInputErrorResult.h
/usr/include/libinvm-cli/NotImplementedErrorResult.h
/usr/include/libinvm-cli/ObjectListResult.h
/usr/include/libinvm-cli/OutputOptions.h
/usr/include/libinvm-cli/OutputOptionsValidator.h
/usr/include/libinvm-cli/ParseErrorResult.h
/usr/include/libinvm-cli/Parser.h
/usr/include/libinvm-cli/PropertyListResult.h
/usr/include/libinvm-cli/ResultBase.h
/usr/include/libinvm-cli/SimpleListResult.h
/usr/include/libinvm-cli/SimpleResult.h
/usr/include/libinvm-cli/SyntaxErrorBadValueResult.h
/usr/include/libinvm-cli/SyntaxErrorMissingValueResult.h
/usr/include/libinvm-cli/SyntaxErrorResult.h
/usr/include/libinvm-cli/SyntaxErrorUnexpectedValueResult.h
/usr/include/libinvm-cli/Trace.h
/usr/include/libinvm-cli/cr_i18n.h
/usr/include/libinvm-cli/osAdapter.h
/usr/include/libinvm-i18n/libIntel_i18n.h
/usr/lib64/libinvm-cim.so
/usr/lib64/libinvm-cli.so
/usr/lib64/libinvm-i18n.so
/usr/lib64/libixpdimm-cim.so
/usr/lib64/libixpdimm-cli.so
/usr/lib64/libixpdimm-common.so
/usr/lib64/libixpdimm-core.so
/usr/lib64/libixpdimm.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libinvm-cim.so.1
/usr/lib64/libinvm-cim.so.1.0.0
/usr/lib64/libinvm-cli.so.1
/usr/lib64/libinvm-cli.so.1.0.0
/usr/lib64/libinvm-i18n.so.1
/usr/lib64/libinvm-i18n.so.1.0.0
/usr/lib64/libixpdimm-cim.so.99
/usr/lib64/libixpdimm-cim.so.99.99.0
/usr/lib64/libixpdimm-cli.so.99
/usr/lib64/libixpdimm-cli.so.99.99.0
/usr/lib64/libixpdimm-common.so.99
/usr/lib64/libixpdimm-common.so.99.99.0
/usr/lib64/libixpdimm-core.so.99
/usr/lib64/libixpdimm-core.so.99.99.0
/usr/lib64/libixpdimm.so.99
/usr/lib64/libixpdimm.so.99.99.0
